### ISSUE TITLE
EnvoyProxyReference in integration tests is not optional

### ISSUE THREAD

**Issue by emil-jacero** [jacero-io/kode-operator#32]
When omitting EnvoyProxyReference in "production" it allows it. However when i attempt to omit it for an integration test it fails.

## Error

```
  [FAILED] Expected success, but got an error:
      <*errors.StatusError | 0x14000407540>: 
      KodeClusterTemplate.kode.jacero.io "test-kodetemplate-without-envoy" is invalid: spec.envoyProxyRef.kind: Unsupported value: "": supported values: "EnvoyProxyConfig", "EnvoyProxyClusterConfig"
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "KodeClusterTemplate.kode.jacero.io \"test-kodetemplate-without-envoy\" is invalid: spec.envoyProxyRef.kind: Unsupported value: \"\": supported values: \"EnvoyProxyConfig\", \"EnvoyProxyClusterConfig\"",
              Reason: "Invalid",
              Details: {
                  Name: "test-kodetemplate-without-envoy",
                  Group: "kode.jacero.io",
                  Kind: "KodeClusterTemplate",
                  UID: "",
                  Causes: [
                      {
                          Type: "FieldValueNotSupported",
                          Message: "Unsupported value: \"\": supported values: \"EnvoyProxyConfig\", \"EnvoyProxyClusterConfig\"",
                          Field: "spec.envoyProxyRef.kind",
                      },
                  ],
                  RetryAfterSeconds: 0,
              },
              Code: 422,
          },
      }
  In [BeforeAll] at: /Users/emil/devel/emil/kode-operator/test/integration/controller/kode_integration_test.go:105 @ 07/08/24 09:57:40.873
```

## Config

`envoyProxyRef` is omitted.

```yaml
---
apiVersion: kode.jacero.io/v1alpha1
kind: KodeTemplate
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: kodetemplate-codeserver-sample
  namespace: default
spec:
  type: code-server
  image: linuxserver/code-server:latest
  tz: "Europe/Stockholm"
  puid: 1000
  pgid: 1000
  defaultHome: /config
  defaultWorkspace: workspace

```
